### ISSUE TITLE
Possible config option for Thundestore mod loader

### ISSUE THREAD

**Issue by Canti-sama** [helo1223/LC_VoiceHUD#1]
Not sure if this is the right place, but would it be possible to add an option to revert the color changing aspect via the Thunderstore config?

**Comment by helo1223** [comment]
Sure, I'll find out how I can do that and I'll put that in the next release :)

Are the color ranges too sensitive or do you just prefer the default color?

**Comment by Canti-sama** [comment]
I just prefer the original solid white/grey
